# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='withings_api',
    version='2.1.4b0',
    description='Library for the Withings API',
    python_requires='<4.0,>=3.5',
    project_urls={
        "homepage": "https://github.com/vangorra/python_withings_api",
        "repository": "https://github.com/vangorra/python_withings_api"
    },
    author='Robbie Van Gorkom',
    author_email='robbie.van.gorkom@protonmail.com',
    license='MIT',
    keywords='withings api',
    packages=['withings_api'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'arrow>=0.15.2', 'requests-oauth>=0.4.1', 'requests-oauthlib>=1.2'
    ],
    extras_require={
        "dev": [
            "black==19.3b0; python_version == \"3.*\" and python_version >= \"3.7.0\"",
            "coverage==4.5.4", "flake8==3.7.8", "isort==4.3.21", "mypy==0.740",
            "pydocstyle==4.0.1", "pylint==2.4.3", "pytest==5.2.1",
            "pytest-cov==2.8.1", "responses==0.10.6", "toml==0.10.0",
            "wheel==0.33.6"
        ]
    },
)
